/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.martinamolina;
import jdbc.martinamolina.view.biblioteca.BibliotecaView;
import jdbc.martinamolina.controller.biblioteca.LibroController;

import jdbc.martinamolina.view.productos.ProductosView;
import jdbc.martinamolina.controller.productos.ProductoController;

import jdbc.martinamolina.controller.alumnos.EstudiantesController;
import jdbc.martinamolina.view.estudiantes.EstudiantesView;

import javax.swing.*;
/**
 *
 * @author Mar
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        wireEvents();
    }
    private void wireEvents() {
        btnBiblioteca.addActionListener(e -> abrirBiblioteca());
        btnProductos.addActionListener(e -> abrirProductos());
       btnEstudiantes.addActionListener(e -> abrirEstudiantes());
        
    }

    private void abrirBiblioteca() {
        BibliotecaView v = new BibliotecaView();
        v.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        new LibroController(v);              // el controller ya setea listeners y (si querés) hace visible
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        // Si querés esconder el menú mientras tanto:
        // this.setVisible(false);
        // v.addWindowListener(new java.awt.event.WindowAdapter() {
        //     @Override public void windowClosed(java.awt.event.WindowEvent e) { Menu.this.setVisible(true); }
        // });
    }
    
    private void abrirProductos() {
        ProductosView v = new ProductosView();
        v.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        new ProductoController(v);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }
    private void abrirEstudiantes() {
    EstudiantesView v = new EstudiantesView();
    v.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    new EstudiantesController(v);    // si tu controller existe y recibe la vista
    v.setLocationRelativeTo(this);
    v.setVisible(true);

    // (opcional) ocultar menú mientras está abierta la vista y restaurarlo al cerrar:
    // this.setVisible(false);
    // v.addWindowListener(new java.awt.event.WindowAdapter() {
    //     @Override public void windowClosed(java.awt.event.WindowEvent e) {
    //         menu.this.setVisible(true);
    //     }
    // });
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        btnBiblioteca = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMAS");

        btnEstudiantes.setText("Estudiantes");

        btnBiblioteca.setText("Biblioteca");

        btnProductos.setText("Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        SwingUtilities.invokeLater(()->new menu().setVisible(true));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
